### ISSUE TITLE
Can't require it when use irb.

### ISSUE THREAD

**Issue by kfihihc** [bfoz/gerber#22]
Hi, bfoz,

I want to parser a gerber file in my Mac OS X 10.9. But it seem can't work.

Log:

```
LoadError: cannot load such file -- units
from /Users/xiaobo/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from /Users/xiaobo/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from /Users/xiaobo/.rvm/gems/ruby-2.1.1/gems/gerber-1/lib/gerber.rb:2:in `<top (required)>'
from /Users/xiaobo/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `require'
from /Users/xiaobo/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
from /Users/xiaobo/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
from (irb):1
from /Users/xiaobo/.rvm/rubies/ruby-2.1.1/bin/irb:11:in `<main>'
```

**Comment by bfoz** [comment]
The gerber gem requires the units gem, and it appears that the dependency isn't set up yet. Thanks for catching that.

In the meantime, you can work around this by manually installing the units gem from: https://github.com/bfoz/units-ruby

NOTE: Don't install the units gem from rubygems.org, it won't work.

**Comment by kfihihc** [comment]
Yes, I fixed it.

I install the gerber gem and units-ruby gem in local.

And, Did you have plan to integrate SVG or PNG/JPGE's generator?

**Comment by bfoz** [comment]
I'm glad you got it working. Let me know if you need anything else.

I don't plan on adding image export to Gerber because there are just too many formats to handle. Ideally I'd like to export to some sort of intermediary object (something like a canvas) that all of the image format gems can import. But that's still a long ways off.
